# Nginx UI Template Start
name = "Hello Header"
author = "@Hintay"
description = { en = "Adds an X-Hello response header", zh_CN = "添加 X-Hello 响应头" }
# Nginx UI Template End
add_header X-Hello "world" always;
